### ISSUE TITLE
Postgres failing for integers?

### ISSUE THREAD

**Issue by cigrainger** [elixir-explorer/adbc#55]
With SQLite:

```elixir
{:ok, _} = Adbc.Connection.query(conn, "select 123;")
{:ok, %Adbc.Result{num_rows: nil, data: %{"123" => ~c"{"}}}
```

With Postgres:

```elixir
{:ok, _} = Adbc.Connection.query(conn, "select 123;")
{:ok, %Adbc.Result{num_rows: nil, data: %{"?column?" => ~c"{"}}}
```

But strings at least seem fine:

```elixir
{:ok, %Adbc.Result{num_rows: nil, data: %{"?column?" => ["abc"]}}}
```

**Comment by josevalim** [comment]
~c"" is a charlist, so you are indeed getting [123] back, but shown as a charlist. :)

**Comment by cigrainger** [comment]
@josevalim Maybe there's an issue with Explorer then? Because `{:ok, _} = DataFrame.from_query(conn, "select 123;")` raises:
```elixir
** (MatchError) no match of right hand side value: {:error, "Generic Error: cannot cast to dtype: i32"}
    (explorer 0.7.2) lib/explorer/polars_backend/shared.ex:101: Explorer.PolarsBackend.Shared.df_dtypes/1
    (explorer 0.7.2) lib/explorer/polars_backend/shared.ex:87: Explorer.PolarsBackend.Shared.create_dataframe/1
    (explorer 0.7.2) lib/explorer/polars_backend/data_frame.ex:34: Explorer.PolarsBackend.DataFrame.from_query/3
    #cell:qihbhy2uwgl4ljpx:1: (file)
    ```
    
    Let me check if this is also happening on main.

**Comment by josevalim** [comment]
That's fixed in main because we support i32 and all other types now!

**Comment by josevalim** [comment]
(Explorer main)

**Comment by cigrainger** [comment]
Thanks :) I might need to cut a release then.
